In [2]:
import numpy as np

In [3]:
a = np.zeros((3,5), dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

In [4]:
b = np.ones(5)
print(b)

[1. 1. 1. 1. 1.]

In [5]:
c = np.full(10,5)
print(c)

[5 5 5 5 5 5 5 5 5 5]

In [6]:
d = np.arange(10,50,5)
print(d)

[10 15 20 25 30 35 40 45]

In [7]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**Multi Dimensional Arrays**

In [8]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
f = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
         )

In [10]:
f[2,:]

array([7, 8, 9])

In [11]:
## randomly generated arrays

np.random.seed(2) ## makes sure that the random numbers are the same every time you run the code
np.random.rand(5,4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149, 0.07964548]])

In [12]:
## randomly generated arrays

np.random.seed(3) ## makes sure that the random numbers are the same every time you run the code
np.random.randn(5,4) ## generates random numbers from a normal distribution with mean 0 and standard deviation 1

array([[ 1.78862847,  0.43650985,  0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898, -0.08274148, -0.62700068],
       [-0.04381817, -0.47721803, -1.31386475,  0.88462238],
       [ 0.88131804,  1.70957306,  0.05003364, -0.40467741],
       [-0.54535995, -1.54647732,  0.98236743, -1.10106763]])

In [13]:
np.random.seed(4)
np.random.randint(low=0,high=1000,size=(5,5))

array([[122, 174, 439, 709, 897],
       [360, 599, 456, 818, 393],
       [ 58, 764, 871, 109, 606],
       [823, 951, 313, 872, 676],
       [946,  44, 294, 126, 564]])

**element wise operations**

In [14]:
a = np.arange(5)
print(a)

a+1

[0 1 2 3 4]

array([1, 2, 3, 4, 5])

In [15]:
import pandas as pd

In [16]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [17]:
df = pd.DataFrame(data, columns=columns)
print(df)

      Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC
2    Lotus     Elise  2010      218.0                 4            MANUAL
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC
4   Nissan  Frontier  2017      261.0                 6            MANUAL

  Vehicle_Style   MSRP
0         sedan   2000
1         Sedan  27150
2   convertible  54990
3       4dr SUV  34450
4        Pickup  32340

In [18]:
df['Make']
#df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [19]:
df[['Make', 'Engine HP', 'MSRP']]

      Make  Engine HP   MSRP
0   Nissan      138.0   2000
1  Hyundai        NaN  27150
2    Lotus      218.0  54990
3      GMC      194.0  34450
4   Nissan      261.0  32340

In [20]:
df.index #shows the index of the dataframe which means the row numbers
df.Make.index #shows the index of the series which means the row numbers

RangeIndex(start=0, stop=5, step=1)

In [21]:
df['id'] = ['a','b','c','d','e'] #adds a new column to the dataframe
df.set_index('id') #sets the index of the dataframe to the 'id' column
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,a
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,b
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,c
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,d
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,e

In [22]:
df.iloc[[1,2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,b
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,c

In [23]:
df.reset_index(drop=True, inplace=True) #resets the index of the dataframe to the default integer index
df.drop(columns=['level_0', 'index'], inplace=True, errors='ignore')
df = df.reset_index(drop=True) #resets the index of the dataframe to the default integer index
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,a
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,b
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,c
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,d
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,e

In [24]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,a
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,b
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,c
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,d
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,e

In [25]:
df['Engine HP']/100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [26]:
df[
    (df['Year'] > 2015) & (df['Make'] == 'Nissan')
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,e

In [27]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.lower() 
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_')
df['Vehicle_Style']

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: str

In [28]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [29]:
df.describe().round(1)

         Year  Engine HP  Engine Cylinders     MSRP
count     5.0        4.0               5.0      5.0
mean   2010.4      202.8               4.4  30186.0
std      11.3       51.3               0.9  18985.0
min    1991.0      138.0               4.0   2000.0
25%    2010.0      180.0               4.0  27150.0
50%    2017.0      206.0               4.0  32340.0
75%    2017.0      228.8               4.0  34450.0
max    2017.0      261.0               6.0  54990.0

In [30]:
df.describe(include='all')

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
count,5,5,5.000000,4.00000,5.000000,5,5,5.000000,5
unique,4,5,NaN,NaN,NaN,2,4,NaN,5
top,Nissan,Stanza,NaN,NaN,NaN,MANUAL,sedan,NaN,a
freq,2,1,NaN,NaN,NaN,3,2,NaN,1
mean,NaN,NaN,2010.400000,202.75000,4.400000,NaN,NaN,30186.000000,NaN
std,NaN,NaN,11.260551,51.29896,0.894427,NaN,NaN,18985.044904,NaN
min,NaN,NaN,1991.000000,138.00000,4.000000,NaN,NaN,2000.000000,NaN
25%,NaN,NaN,2010.000000,180.00000,4.000000,NaN,NaN,27150.000000,NaN
50%,NaN,NaN,2017.000000,206.00000,4.000000,NaN,NaN,32340.000000,NaN
75%,NaN,NaN,2017.000000,228.75000,4.000000,NaN,NaN,34450.000000,NaN
max,NaN,NaN,2017.000000,261.00000,6.000000,NaN,NaN,54990.000000,NaN

In [31]:

df.Make.nunique

<bound method IndexOpsMixin.nunique of 0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str>

In [32]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
id                   5
dtype: int64

In [33]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [34]:
df.isnull().sum() #shows the number of missing values in each column

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
id                   0
dtype: int64

In [35]:
df.groupby('Transmission Type').agg({'MSRP': 'mean'})

                           MSRP
Transmission Type
AUTOMATIC          30800.000000
MANUAL             29776.666667

In [36]:
df.groupby('Transmission Type').MSRP.mean()
#df.groupby('Transmission Type','MSRP').mean()
df.groupby('Transmission Type').agg({'MSRP': 'mean'})

                           MSRP
Transmission Type
AUTOMATIC          30800.000000
MANUAL             29776.666667

In [37]:
df.groupby(['Transmission Type', 'Make']).MSRP.mean()

Transmission Type  Make
AUTOMATIC          GMC        34450.0
                   Hyundai    27150.0
MANUAL             Lotus      54990.0
                   Nissan     17170.0
Name: MSRP, dtype: float64

In [38]:
# several stats on one column
df.groupby('Transmission Type').agg({'MSRP': ['mean', 'median', 'count']})

                           MSRP
                           mean   median count
Transmission Type
AUTOMATIC          30800.000000  30800.0     2
MANUAL             29776.666667  32340.0     3

In [39]:
df.groupby('Transmission Type').agg({'MSRP': 'mean', 'Engine HP': 'max'})

                           MSRP  Engine HP
Transmission Type
AUTOMATIC          30800.000000      194.0
MANUAL             29776.666667      261.0

In [40]:
df.groupby('Transmission Type').agg(
    avg_price=('MSRP', 'mean'),
    n=('MSRP', 'count')
)

                      avg_price  n
Transmission Type
AUTOMATIC          30800.000000  2
MANUAL             29776.666667  3

In [41]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,a
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150,b
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,c
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450,d
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340,e

In [42]:
df.groupby(['Make','Transmission Type']).agg({'Engine HP':'max'})

                           Engine HP
Make    Transmission Type
GMC     AUTOMATIC              194.0
Hyundai AUTOMATIC                NaN
Lotus   MANUAL                 218.0
Nissan  MANUAL                 261.0

In [43]:
df.groupby(['Year','Make']).agg(
    max_horsepower=('Engine HP','max'),
    avg_price=('MSRP','mean')
)

              max_horsepower  avg_price
Year Make
1991 Nissan            138.0     2000.0
2010 Lotus             218.0    54990.0
2017 GMC               194.0    34450.0
     Hyundai             NaN    27150.0
     Nissan            261.0    32340.0

In [44]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,a
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150,b
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,c
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450,d
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340,e

In [45]:
df.Year.value_counts()

Year
2017    3
1991    1
2010    1
Name: count, dtype: int64

In [46]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000,
  'id': 'a'},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150,
  'id': 'b'},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990,
  'id': 'c'},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450,
  'id': 'd'},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340,
  'id': 'e'}]

In [47]:
u = np.array([1,2,3])
v = np.array([4,5,6])

#u.shape
#v.shape

n = u.shape[0]
print(n)

3

**Vector-Vector Multiplication**

In [48]:
def vector_multiplication (u,v):
    assert u.shape[0] == v.shape[0], "Vectors must be the same shape"
    n = u.shape[0] # assigns the total value of the first dimension of the array to n which is the number of elements in the vector

    result = 0.0

    for i in range(n):
        result = result + u[i]*v[i]

    return result

    #return np.dot(u,v)
    # return u*v #Hadamard product

vector_multiplication(u,v)

np.float64(32.0)

**Matrix-Vector Multiplication**

In [ ]:
## computing matrix-vector multiplication

## a is a 3x4 matrix
a = np.array(
    [[1,2,3,4],
     [4,5,6,6],
     [7,8,9,10]
     ])
## b is a vector
b = np.array([10,11,12,13])

#a.shape
a.shape[0] #shows the number of rows in the array
a.shape[1] #shows the number of columns in the array

n_mat1 = a.shape[0] ## assigns the number of rows in the first matrix
n_mat2 = a.shape[1] ## assigns the number of columns in the first matrix

result = np.zeros(n_mat1)

def matrix_vector_multiplication(a,b):

    assert a.shape[1] == b.shape[0]
    

    for i in range(n_mat1): 
        for j in range(n_mat2):
            result[i] = result[i] + a[i,j]*b[j]
    return result

matrix_vector_multiplication(a,b)

array([120., 245., 396.])

**Matrix-Matrix Multiplication**

In [55]:
num_rows = U.shape[0]
num_cols = V.shape[1]

result = np.zeros((num_rows,num_cols))

def matrix_matrix_multiplication(a,b):

    assert U.shape[1] == V.shape[0]

    for i in range(num_cols): 
        vi = V[:,1]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi
    return result

NameError: name 'U' is not defined