## Homework 3: Pranav Prakash
2026 lead-scoring dataset

In [1]:
%pip install -q kagglehub pandas
import pandas as pd
from pathlib import Path
from urllib.request import urlretrieve

url = (
    "https://raw.githubusercontent.com/DataTalksClub/"
    "machine-learning-zoomcamp/main/cohorts/2026/data/"
    "course_lead_scoring_2026.csv"
)

file_path = Path("course_lead_scoring_2026.csv")

if not file_path.exists():
    urlretrieve(url, file_path)

df = pd.read_csv(file_path)

df.head()

Note: you may need to restart the kernel to use updated packages.

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [2]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [3]:
df.columns
df.isnull().sum()
df.dtypes
# look at the distince values in each column
df.nunique()
# look at the count of distinct values in each column including the values 
df.value_counts()

df.iloc[:100]

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
95,paid_ads,retail,unemployed,asia,21084.0,4,9,0.68,1
96,referral,finance,employed,asia,75202.0,2,5,0.59,1
97,events,technology,unemployed,europe,50096.0,1,0,0.18,0
98,organic_search,technology,employed,europe,95649.0,1,1,0.37,1
99,events,retail,self_employed,africa,34621.0,2,4,0.50,1

In [34]:
## Define the column names into variable types
categorical = list(df.columns[df.dtypes == 'str'])
numerical = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

df[categorical] = df[categorical].fillna('NA')
df[categorical].iloc[:100]
df[numerical] = df[numerical].fillna(0)
df[numerical].iloc[:100]

,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,88160.0,3,4,0.64,1
1,72688.0,3,7,0.72,1
2,44697.0,3,4,0.58,1
3,0.0,3,6,0.57,0
4,24062.0,4,5,0.62,1
...,...,...,...,...,...
95,21084.0,4,9,0.68,1
96,75202.0,2,5,0.59,1
97,50096.0,1,0,0.18,0
98,95649.0,1,1,0.37,1
99,34621.0,2,4,0.50,1